In [2]:
from google.colab import drive
drive.mount('/Content')

Mounted at /Content


In [7]:
import cv2
import numpy as np

image = cv2.imread('/Content/MyDrive/SD_card_synced/Test Images/images/aeval1.jpg')
# type(image)
# image.shape
print(f"{image[0:10]}")

[[[248 248 248]
  [248 248 248]
  [240 248 240]
  ...
  [144 148 144]
  [136 144 144]
  [144 144 144]]

 [[240 248 240]
  [240 248 248]
  [240 248 240]
  ...
  [144 148 144]
  [136 140 136]
  [136 136 144]]

 [[224 232 232]
  [232 236 232]
  [240 248 240]
  ...
  [144 148 152]
  [144 144 136]
  [144 144 144]]

 ...

 [[224 228 224]
  [232 236 232]
  [248 248 248]
  ...
  [152 152 152]
  [144 144 144]
  [144 144 144]]

 [[232 236 232]
  [224 228 224]
  [232 240 240]
  ...
  [144 144 144]
  [144 144 144]
  [144 148 144]]

 [[232 240 240]
  [248 248 240]
  [248 248 248]
  ...
  [136 140 136]
  [144 148 144]
  [144 144 144]]]
